config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'users#index'

  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :questions, except: [:show, :new, :index]
  resources :hashtags, only: :show, param: :text
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  REGEXP = /\#[[:alpha:]\_\-]+/u

  has_many :hashtag_questions, dependent: :destroy
  has_many :questions, through: :hashtag_questions

  scope :with_questions, -> { where_exists(:hashtag_questions).order(:created_at) }

  validates :text, presence: true, uniqueness: true
end

app/models/hashtag_question.rb
class HashtagQuestion < ApplicationRecord
  belongs_to :hashtag
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :hashtag_questions, dependent: :destroy
  has_many :hashtags, through: :hashtag_questions

  belongs_to :user
  belongs_to :author, class_name: 'User', optional: true

  validates :text, length: { maximum: 255 }, presence: true

  after_commit :create_hashtags, on: [:create, :update]

  private

  def create_hashtags
    self.hashtags =
        "#{answer} #{text}".
            downcase.
            scan(Hashtag::REGEXP).
            uniq.
            map { |ht| Hashtag.find_or_create_by(text: ht.delete('#')) }
  end
end

app/models/user.rb
require 'openssl'

class User < ApplicationRecord
  # параметры работы модуля шифрования паролей
  ITERATIONS = 20000
  DIGEST = OpenSSL::Digest::SHA256.new

  ALLOWED_USERNAME = /\A[a-z\d_]+\z/
  ALLOWED_EMAIL = /.+@.+\..+/
  ALLOWED_COLOR = /\A#([[:xdigit:]]{3}){1,2}\z/

  attr_accessor :password

  has_many :questions, dependent: :destroy
  has_many :no_anon_questions, class_name: 'Question', foreign_key: :author_id, dependent: :nullify

  validates :username, length: { maximum: 40 }, presence: true, uniqueness: true, format: { with: ALLOWED_USERNAME }

  validates :email, presence: true, uniqueness: true, format: { with: ALLOWED_EMAIL }

  validates :color, format: { with: ALLOWED_COLOR }

  validates_presence_of :password, on: :create
  validates_confirmation_of :password

  before_validation :username_downcase, :email_downcase
  before_save :encrypt_password

  def self.authenticate(email, password)
    user = find_by(email: email)

    # Сравниваются password_hash, оригинальный пароль нигде не сохраняется вообще
    if user.present? && user.password_hash == User.hash_to_string(OpenSSL::PKCS5.pbkdf2_hmac(password, user.password_salt, ITERATIONS, DIGEST.length, DIGEST))
      user
    else
      nil
    end
  end

  # служебный метод, преобразующий бинарную строку в 16-ричный формат
  def self.hash_to_string(password_hash)
    password_hash.unpack('H*')[0]
  end

  def encrypt_password
    if self.password.present?
      # создаём соль
      self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))

      # создаём хэш пароля
      self.password_hash = User.hash_to_string(
          OpenSSL::PKCS5.pbkdf2_hmac(self.password, self.password_salt, ITERATIONS, DIGEST.length, DIGEST)
      )
    end
  end

  private

  def email_downcase
    self.email = email&.downcase
  end

  def username_downcase
    self.username = username&.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def reject_user
    redirect_to root_path, alert: 'Доступ только авторизованным пользователям.'
  end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  def show
    @hashtag = Hashtag.with_questions.find_by!(text: params[:text])
    @questions = @hashtag.questions
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :load_question, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, except: [:create]

  def edit
  end

  def create
    @question = Question.new(question_params)
    @question.author = current_user
    if @question.save
      redirect_to user_path(@question.user), notice: 'Вопрос успешно задан.'
    else
      render :edit
    end
  end

  def update
    if @question.update(question_params)
      redirect_to user_path(@question.user), notice: 'Вопрос успешно сохранён.'
    else
      render :edit
    end
  end

  def destroy
    user = @question.user
    @question.destroy
    redirect_to user_path(user), notice: 'Вопрос успешно удалён.'
  end

  private

  def authorize_user
    reject_user unless @question.user == current_user
  end

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    if current_user.present?
      if params[:question][:user_id].to_i == current_user.id
        params.require(:question).permit(:user_id, :text, :answer, :author_id)
      else
        params.require(:question).permit(:user_id, :text, :author_id)
      end
    else
      params.require(:question).permit(:user_id, :text)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])

    if user.present?
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Вы успешно аутентифицировались.'
    else
      flash.now.alert = 'Неправильная почта или пароль.'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Выход успешно совершён. Ждём вас снова.'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, except: [:index, :new, :create]
  before_action :authorize_user, except: [:index, :new, :create, :show]

  def index
    @users = User.all
    @hashtags = Hashtag.with_questions
  end

  def new
    redirect_to root_path, alert: 'Вы уже зашли в систему.' if current_user.present?
    @user = User.new
  end

  def create
    redirect_to root_path, alert: 'Вы уже зашли в систему.' if current_user.present?
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: 'Пользователь успешно зарегистрирован!'
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'Данные обновлены!'
    else
      render 'edit'
    end
  end

  def edit
  end

  def destroy
    session[:user_id] = nil
    @user.destroy
    flash[:success] = "Пользователь удален."
    redirect_to root_path
  end

  def show
    @questions = @user.questions.order(created_at: :desc)

    @answers_count = @questions.where.not(answer: nil).count

    @new_question = @user.questions.build
  end

  private

  def authorize_user
    reject_user unless @user == current_user
  end

  def load_user
    @user ||= User.find params[:id]
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :username, :avatar_url, :color)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(user)
    if user.avatar_url.present?
      user.avatar_url
    else
      asset_path 'avatar.jpg'
    end
  end

  def sklonyator (quantity, form1, form2, form3)
    if (11..14).include?(quantity % 100)
      form3
    elsif quantity % 10 == 1
      form1
    elsif (2..4).include?(quantity % 10)
      form2
    else
      form3
    end
  end

  def fa_icon(icon_class)
    content_tag 'span', '', class: "fa fa-#{icon_class}"
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def text_with_hashtag_link(text)
    text.gsub(Hashtag::REGEXP) { |ht| link_to ht, hashtag_path(ht.delete('#').downcase) }.html_safe
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hashtags/show.html.erb
<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
    <h1 class="title-medium"><%= @hashtag.text %></h1>
  </div>

  <div class="flex-section-row">
    <% @questions.each do |question|%>
      <div class="question-content">
        <div class="question-text text-lead">
          <%= question.text %>
        </div>
        <div class="question-answer text-lead">
          <%= question.answer %>
        </div>
        <div class="question-text">
          <%= link_to question.user.username, user_path(question.user), class: "author-link" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Хорошие вопросы </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class="header">
      <div class="container">
        <div class="header-logo">
          <h1 class="header-title"><%= link_to "Хорошие вопросы", root_path %></h1>
        </div>

        <div class="header-nav">
          <% if current_user %>
            <%= link_to "@#{current_user.username}", user_path(current_user) %> |
            <%= link_to 'Выйти', session_path, data: { method: :delete } %>
          <% else %>
            <%= link_to 'Зарегистрироваться', new_user_path, class: 'button button-light button-small' %>
            <%= link_to 'Войти', new_session_path, class: 'button button-light button-small' %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="content">
      <div class="container">
        <% if flash.any? %>
          <div class="content-wrapper buffer-both">
            <% flash.each do |name, message| %>
              <%= content_tag :div, message, class: "flash-#{name}" %>
            <% end %>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<div class="form">
  <%= form_for(@question) do |f| %>
    <% if @question.errors.any? %>
      <div class="form-errors">
        <ul>
          <% @question.errors.full_messages.each do |message| %>
            <li class="form-error-message"><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.hidden_field :user_id %>

    <div class="form-field">
      <%= f.label :text, 'Вопрос', class: 'form-label' %>
      <%= f.text_area :text, class: 'form-textarea' %>
    </div>

    <% if current_user.present? && current_user == @question.user %>
      <div class="form-field">
        <%= f.label :answer, 'Ответ', class: 'form-label' %>
        <%= f.text_area :answer, class: 'form-textarea' %>
      </div>
    <% end %>

    <div class="form-action buffer-both">
      <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
      или
      <%= link_to "вернуться", user_path(@question.user) %>
    </div>
  <% end %>
</div>

app/views/questions/_question.html.erb
<div class="question">
  <div class="question-content">
    <div class="question-text text-lead">
      <%= text_with_hashtag_link(question.text) %>
    </div>

    <% if question.answer.present? %>
      <div class="question-answer text-lead">
        <%= text_with_hashtag_link(question.answer) %>
      </div>
    <% end %>

    <% if question.author.present? %>
      <div class="question-date">
        Вопрос от <%= link_to "@#{question.author.username}", user_path(question.author) %>
      </div>
    <% end %>

    <div class="question-date">
      <%= l(question.created_at, format: :short) %>
    </div>
  </div>

  <% if question.user == current_user %>
    <% edit_icon = question.answer.blank? ? 'reply' : 'pencil' %>
    <div class="question-actions">
      <%= link_to fa_icon(edit_icon), edit_question_path(question) %>
      <%= link_to fa_icon('trash-o'), question_path(question), method: :delete, data: {confirm: 'Точно удалить вопрос?'} %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Вопрос</h1>

  <div class="column-1-2">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Настройки профиля</h1>

  <div class="column-1-2">
    <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-field">
        <%= f.label 'Никнейм:', class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label 'Ваше имя:', class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label 'URL вашей аватарки:', class: 'form-label' %>
        <%= f.text_field :avatar_url, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label 'Цвет фона вашего профиля:', class: 'form-label color-form' %>
        <%= f.color_field :color, class: 'color-form' %>
      </div>

      <div class="buffer-top-large buffer-bottom">
        Если не хотите менять пароль — оставьте эти поля пустыми!
      </div>

      <div class="form-field">
        <%= f.label 'Пароль:', class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label 'Пароль, ещё раз:', class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="form-action buffer-top">
        <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
      </div>
    <% end %>

    <div class="buffer-top-large">
      <%=
        link_to "Удалить профиль",
                @user,
                method: :delete,
                data: { confirm: "Вы уверены?"},
                class: 'button button-gray button-small'
      %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
    <h1 class="title-medium">Наши пользователи</h1>
  </div>

  <% @users.each do |user| %>
    <div class="users-list-item">
      <div class="user-image-div user-image-div-small">
        <%= link_to image_tag(user_avatar(user), class: 'user-image'), user_path(user) %>
      </div>
      <div class="question-text">
        <%= user.username %>
      </div>
    </div>
  <% end %>

  <div class="text-left buffer-top-large">
    <% @hashtags.each do |hashtag| %>
      <span class="buffer-both">
        <%= link_to "##{hashtag.text}", hashtag_path(hashtag.text), class: 'author-link' %>
      </span>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Присоединяйся к нам!</h1>

  <div class="column-1-2">
    <div class="form">
      <%= form_for @user do |f| %>

        <% if @user.errors.any? %>
          <div class="form-errors">
            <ul>
              <% for message in @user.errors.full_messages %>
                <li class="form-error-message"><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-field">
          <%=f.label :email, 'Логин (email)', class: 'form-label' %>
          <%=f.text_field :email, class: 'form-text-field' %>
        </div>

        <div class="form-field">
          <%=f.label :username, 'Никнейм', class: 'form-label' %>
          <%=f.text_field :username, class: 'form-text-field' %>
        </div>

        <div class="form-field">
          <%=f.label :name, 'Имя', class: 'form-label' %>
          <%=f.text_field :name, class: 'form-text-field' %>
        </div>

        <div class="form-field">
          <%=f.label :password, 'Пароль', class: 'form-label' %>
          <%=f.password_field :password, class: 'form-text-field' %>
        </div>

        <div class="form-field">
          <%=f.label :password_confirmation, 'Пароль, ещё раз', class: 'form-label' %>
          <%=f.password_field :password_confirmation, class: 'form-text-field' %>
        </div>

        <div class="form-action">
          <%=f.submit 'Зарегистрироваться', class: 'button button-small button-dark' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-header text-center" style="background: <%= @user.color %>">
  <h1 class="title-medium">
    <%= @user.name %>
  </h1>

  <div class="buffer-both">
    <%= link_to 'Редактировать профиль', edit_user_path(@user) if current_user == @user %>
  </div>

  <div class="user-image-div">
    <%= image_tag user_avatar(@user), class: 'user-image', alt: '[Фото]' %>
  </div>

  <h2 class="title-small buffer-both">
    @<%= @user.username %>
  </h2>

  <div class="user-ask-button container text-center">
    <%= link_to "Спроси меня", '', class: 'button button-light', id: 'ask-button' %>
  </div>
</div>

<div class="user-question-form-div column-1-4 column-1-4-right" id="ask-form">
  <div class="user-question-form buffer-both">
    <div class="form">
      <%= form_for @new_question do |f| %>
        <%= f.hidden_field :user_id %>

        <div class="form-field">
          <%= f.label "Ваш вопрос для @#{@user.username}", class: 'form-label' %>
          <%= f.text_area :text, class: 'form-textarea' %>
        </div>

        <div class="form-action">
          <%= submit_tag 'Задать вопрос', class: 'button button-small button-dark' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="column-3-4">
  <div class="user-questions buffer-both">
    <div class="buffer-left user-statistics">
      <h3 class="title-small">
        Пользователю задали <%= @questions.length %> <%= sklonyator(@questions.length,'вопрос','вопроса','вопросов' ) %>:
      </h3>
      <p class="text-medium">
        Он ответил на <%= @answers_count %>.
      </p>
    </div>
    <div class="questions-list">
      <% @questions.each do |question| %>
        <%= render partial: 'questions/question', object: question %>
      <% end %>
    </div>
  </div>
</div>